name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create zip archive
        run: |
          cd dist
          zip -r ../fora-web-build.zip .
          cd ..

      - name: Get commit info
        id: commit
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "date=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ steps.commit.outputs.sha }}
          name: Build ${{ steps.commit.outputs.sha }}
          body: |
            **Commit:** ${{ steps.commit.outputs.sha }}
            **Message:** ${{ steps.commit.outputs.message }}
            **Date:** ${{ steps.commit.outputs.date }}

            This is an automated build release for commit ${{ steps.commit.outputs.sha }}.
          files: fora-web-build.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
